# Generated by Django 4.2.13 on 2025-02-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='etkinlikler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etkinlik_adi', models.CharField(max_length=200)),
                ('etkinlik_aciklama', models.TextField()),
                ('etkinlik_tarihi', models.DateField()),
                ('etkinlik_resim', models.FileField(blank=True, upload_to='etkinlikler/', verbose_name='Etkinlik Resmi')),
                ('etkinlik_yeri', models.CharField(max_length=200)),
                ('etkinlik_linki', models.CharField(max_length=200)),
                ('etkinlik_organizator', models.CharField(max_length=200)),
                ('etkinlik_fiyati', models.FloatField(default=0)),
                ('etkinlik_katitim_sayisi', models.IntegerField(default=0)),
            ],
        ),
    ]
