# Generated by Django 4.2.13 on 2025-02-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlikler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlikler',
            name='etkinlik_tarihi',
            field=models.DateTimeField(),
        ),
    ]
