# Generated by Django 4.2.13 on 2025-02-04 14:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlikler', '0002_alter_etkinlikler_etkinlik_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlikler',
            name='etkinlik_bilgilendirmesi',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
