# Generated by Django 4.2.13 on 2025-02-05 12:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlikler', '0003_etkinlikler_etkinlik_bilgilendirmesi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlikler',
            name='etkinlik_bilgilendirmesi',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
