# Generated by Django 4.2.13 on 2025-02-05 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlikler', '0004_alter_etkinlikler_etkinlik_bilgilendirmesi'),
    ]

    operations = [
        migrations.CreateModel(
            name='etkinlik_sepeti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katilimci', models.CharField(max_length=200)),
                ('katilimci_email', models.EmailField(max_length=254)),
                ('katilimci_telefon', models.CharField(max_length=200)),
                ('satin_alama_durumu', models.BooleanField(default=False)),
                ('satin_alma_tarihi', models.DateTimeField(blank=True, null=True)),
                ('elden_satis', models.BooleanField(default=False)),
                ('elden_satis_yapilan_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='etkinlikler',
            name='koltuk_duzeni_var_mi',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='sepet_koltuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koltuk_no', models.IntegerField()),
                ('etkinlik_sepeti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etkinlikler.etkinlik_sepeti')),
            ],
        ),
        migrations.CreateModel(
            name='etkinlik_yorumlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum_yapan', models.CharField(max_length=200)),
                ('yorum', models.TextField()),
                ('yorum_tarihi', models.DateTimeField()),
                ('yorum_yapan_ip', models.GenericIPAddressField()),
                ('yorum_yapan_resmi', models.FileField(blank=True, upload_to='yorumlar/', verbose_name='Yorum Yapan Resmi')),
                ('etkinlik_puan', models.IntegerField()),
                ('etkinlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etkinlikler.etkinlikler')),
            ],
        ),
        migrations.AddField(
            model_name='etkinlik_sepeti',
            name='etkinlik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etkinlikler.etkinlikler'),
        ),
        migrations.CreateModel(
            name='etkinlik_koltuk_fiyaatlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koltuk_no', models.IntegerField()),
                ('fiyat', models.FloatField()),
                ('etkinlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etkinlikler.etkinlikler')),
            ],
        ),
        migrations.CreateModel(
            name='etkinlik_bildirimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bildirim_tarihi', models.DateTimeField()),
                ('bildirim_mesaji', models.TextField()),
                ('etkinlik_url', models.CharField(max_length=200)),
                ('etkinlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etkinlikler.etkinlikler')),
            ],
        ),
    ]
