# Generated by Django 4.2.13 on 2025-02-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlikler', '0005_etkinlik_sepeti_etkinlikler_koltuk_duzeni_var_mi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik_sepeti',
            name='toplam_fiyat',
            field=models.FloatField(default=0),
        ),
    ]
