# Generated by Django 4.2.13 on 2025-02-14 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlikler', '0006_etkinlik_sepeti_toplam_fiyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlik_bildirimi',
            name='etkinlik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etkinlikler.etkinlikler'),
        ),
    ]
