# Generated by Django 4.2.13 on 2025-01-31 13:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aciklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_aciklama', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket_adresi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayfa_sirasi', models.BigIntegerField(null=True)),
                ('baner_resim', models.FileField(blank=True, upload_to='banner/', verbose_name='Sayfaya resim Ekleyiniz')),
            ],
        ),
        migrations.CreateModel(
            name='email_adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket_email_adresi', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='hakkimizda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hakkimda', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='iletisim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iletisim_yollari', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='numara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket_numarasi', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='resimler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.FileField(blank=True, upload_to='resimler/', verbose_name='Sayfaya resim Ekleyiniz')),
            ],
        ),
        migrations.CreateModel(
            name='sayfa_iconu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayfa_logo', models.FileField(blank=True, null=True, upload_to='icon/', verbose_name='Sayfaya icon Ekleyin')),
            ],
        ),
        migrations.CreateModel(
            name='sayfa_logosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayfa_logo', models.FileField(blank=True, null=True, upload_to='logo/', verbose_name='Sayfaya Logo Ekleyin')),
            ],
        ),
        migrations.CreateModel(
            name='site_adi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_adi_genel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='sosyalmedyafb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='sosyalmedyaInsgr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='sosyalmedyaTw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400)),
            ],
        ),
    ]
