# Generated by Django 4.2.13 on 2025-02-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_notes_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='duyuru_resmi',
            field=models.FileField(blank=True, upload_to='duyurular/', verbose_name='Duyuru Resmi'),
        ),
    ]
